name: Deploy to EC2

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Build Docker image and list images
        run: |
          docker build -t hospital-app .
          docker tag hospital-app hospital-app:latest
          docker image ls
        working-directory: ${{ github.workspace }} # Add this line

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        run: docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" -p "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: List Docker images
        run: docker image ls
      - name: Tag Docker image for Docker Hub
        run: docker tag hospital-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest
      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    steps:
      - name: SSH and Deploy
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest
            docker stop condescending_mayer || true
            docker rm condescending_mayer || true
            docker run -d --name condescending_mayer -p 80:80 ${{ secrets.DOCKERHUB_USERNAME }}/hospital-app:latest
            echo "Deployment successful!"